
services:
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: Todo-Backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - MONGO_URI=${MONGO_URI}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    container_name: My_Mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge