version: '3.8'

services:
  
  app:
    build: .
    container_name: Project_SUPA
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    container_name: Project_MONGOD
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
